version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root

  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
